### PR TITLE
add sepolicy-inject to fix brevent dumpsys dead

### PR DESCRIPTION
**Pull request by tzhao11**
Fix https://github.com/brevent/Brevent/issues/17

### CODE REVIEW

**Comment by simonsmh** [comment]
Thanks!

**Comment by tzhao11** [comment]
Should I bump the version?

**Comment by liudongmiao** [comment]
Just let you know, the latest Brevent don't use root directly.

Now, Brevent use su to enable network debugging, then connect via SimpleAdb. It's simple shell instead of root.

**Comment by simonsmh** [comment]
I don't want to let users choose adb directly on start for its instability. Only if you have purchased 3$ and enabled "run as root", then this module could working without any problem. Instead, it won't work (start on boot). You may create module yourself with adb and make it official at the same time :)

**Comment by vvb2060** [comment]
Just let you know, because  https://github.com/topjohnwu/Magisk/commit/cfae6c63b5cf74b6ab6752b4660a714ee1b29186 , I updated the script.
I do not know why topjohnwu did it, without any notice.

**Comment by simonsmh** [comment]
What's the difference between `magiskpolicy` and `sepolicy-inject`binary? They both have `--live` @vvb2060

**Comment by liudongmiao** [comment]
Just tell you the `dumpsys` problem. And IMO, some other apps (like force-doze) use `dumpsys` too.

Just for @simonsmh, as it's unstable (mostly magisksu), so Brevent regards Root as experimental features, and payment is required to enable. Otherwise, many people ask why it doesn't work, and then I cannot tell them, just fuck your su provider.

**Pull request merged**
